version: '3.6'

services:
  postgres:
    image: postgres:9.6
    networks:
      - backend
    environment:
      - POSTGRES_PASSWORD=password
  app:
    image: automated_testing:section08
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432
    volumes:
      - .:/code
    command: python app.py
    depends_on:
      - postgres
  newman:
    network_mode: host
    image: postman/newman:alpine
    volumes:
    - .:/code
    command: run /code/tests/system/create-store-item.postman_collection.json -e /code/tests/system/create-store-item.postman_environment.json
    depends_on:
      - postgres
      - app

networks:
  backend:
    driver: overlay
    attachable: true