version: '3.6'

services:
  postgres:
    image: postgres:9.6
    networks:
      - backend
    environment:
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  test:
    image: automated_testing:section08
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432
    volumes:
      - .:/code
    command: ["/wait-for-it/wait-for-it.sh", "postgres:5432", "--", "python", "-m", "unittest", "discover", "-v", "-s", "tests", "-t", ".", "-p", "test_*.py"]
    depends_on:
      - postgres


networks:
  backend:
    driver: overlay
    attachable: true