version: '3.6'

services:
  postgres:
    image: postgres:9.6
    networks:
      - backend
    environment:
      - POSTGRES_PASSWORD=password
  app:
    image: automated_testing:section08
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/postgres
    volumes:
      - .:/code
    command: python app.py
    depends_on:
      - postgres


networks:
  backend:
    driver: overlay
    attachable: true